import type { Article } from './types';

export const mockArticles: Article[] = [
  {
    id: '1',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '로컬에서 실행 가능한 초경량 LLM 프레임워크, 90% 메모리 절감 달성',
    summaryKoBody: '엣지 디바이스에서도 대규모 언어 모델을 구동할 수 있는 혁신적인 최적화 기술을 적용했습니다. 양자화와 프루닝 기법을 결합하여 메모리 사용량을 획기적으로 줄였습니다.',
    titleEn: 'Lightweight LLM Framework for Edge Devices - Achieves 90% Memory Reduction',
    url: 'https://github.com/example/llm-edge',
    score: 1250,
    tags: ['llm', 'edge-computing', 'optimization', 'quantization'],
    createdAtSource: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 1200,
      readTime: '5분',
      language: 'English',
    },
  },
  {
    id: '2',
    itemType: 'BLOG',
    source: 'hackernews',
    category: 'DEVOPS_SRE',
    summaryKoTitle: '쿠버네티스 배포 자동화를 위한 새로운 GitOps 도구 출시',
    summaryKoBody: '복잡한 설정 없이도 GitOps 워크플로우를 구현할 수 있는 도구가 등장했습니다. 기존 ArgoCD나 Flux보다 설정이 간단하며 학습 곡선이 낮습니다.',
    titleEn: 'New GitOps Tool Simplifies Kubernetes Deployments with Zero Configuration',
    url: 'https://news.ycombinator.com/item?id=12345',
    score: 890,
    tags: ['kubernetes', 'gitops', 'devops', 'automation'],
    createdAtSource: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 142,
      readTime: '7분',
    },
  },
  {
    id: '3',
    itemType: 'BLOG',
    source: 'devto',
    category: 'BACKEND',
    summaryKoTitle: 'Spring Boot 3.3에서 가상 스레드로 처리량 10배 향상시킨 실전 가이드',
    summaryKoBody: 'Java 21의 가상 스레드를 Spring Boot에 적용하여 동시 요청 처리 능력을 극대화하는 방법을 다룹니다. 실제 프로덕션 환경에서의 성능 측정 결과도 포함되어 있습니다.',
    titleEn: 'Production Guide: 10x Throughput Improvement with Virtual Threads in Spring Boot 3.3',
    url: 'https://dev.to/example/virtual-threads',
    score: 750,
    tags: ['spring-boot', 'java', 'virtual-threads', 'performance'],
    createdAtSource: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '12분',
    },
  },
  {
    id: '4',
    itemType: 'DISCUSSION',
    source: 'reddit',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'AWS 비용을 70% 절감한 클라우드 아키텍처 최적화 사례',
    summaryKoBody: '스타트업에서 월 10만 달러의 AWS 비용을 3만 달러로 줄인 실제 사례를 공유합니다. Reserved Instances, Spot Instances, 아키텍처 재설계 등 다양한 전략을 사용했습니다.',
    titleEn: 'How We Cut AWS Costs by 70% Through Architecture Optimization',
    url: 'https://reddit.com/r/devops/example',
    score: 645,
    tags: ['aws', 'cost-optimization', 'architecture', 'cloud'],
    createdAtSource: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    metadata: {
      upvotes: 245,
      comments: 89,
    },
  },
  {
    id: '5',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '오픈소스 RAG 파이프라인 - PDF부터 실시간 Q&A까지 5분 내 구축',
    summaryKoBody: '문서를 업로드하면 자동으로 벡터 DB에 저장하고 LLM과 연결하여 질의응답 시스템을 만들어주는 올인원 솔루션입니다. Docker Compose로 간단하게 실행할 수 있습니다.',
    titleEn: 'Open Source RAG Pipeline: From PDF to Real-time Q&A in 5 Minutes',
    url: 'https://github.com/example/rag-pipeline',
    score: 1050,
    tags: ['rag', 'vector-db', 'llm', 'opensource', 'langchain'],
    createdAtSource: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 3500,
      readTime: '8분',
      language: 'Chinese',
    },
  },
  {
    id: '6',
    itemType: 'BLOG',
    source: 'medium',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'Prometheus와 Grafana로 구축하는 완벽한 관측성 스택',
    summaryKoBody: '마이크로서비스 환경에서 필수적인 모니터링과 알림 시스템을 처음부터 끝까지 구축하는 가이드입니다. 실용적인 대시보드 템플릿과 알림 규칙도 제공됩니다.',
    titleEn: 'Building the Perfect Observability Stack with Prometheus and Grafana',
    url: 'https://medium.com/example/observability',
    score: 580,
    tags: ['prometheus', 'grafana', 'observability', 'monitoring'],
    createdAtSource: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '15분',
    },
  },
  {
    id: '7',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: 'Rust로 작성된 초고속 API 게이트웨이, Kong보다 5배 빠른 성능',
    summaryKoBody: 'Rust의 성능과 안전성을 활용한 차세대 API 게이트웨이입니다. 인증, 레이트 리미팅, 로깅 등 핵심 기능을 모두 제공하며 메모리 사용량도 매우 낮습니다.',
    titleEn: 'Ultra-Fast API Gateway in Rust - 5x Faster Than Kong',
    url: 'https://github.com/example/rust-gateway',
    score: 920,
    tags: ['rust', 'api-gateway', 'performance', 'microservices'],
    createdAtSource: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 2100,
      readTime: '10분',
      language: 'English',
    },
  },
  {
    id: '8',
    itemType: 'BLOG',
    source: 'hashnode',
    category: 'AI_LLM',
    summaryKoTitle: 'ChatGPT 플러그인 대신 Function Calling으로 외부 API 연동하기',
    summaryKoBody: 'OpenAI의 Function Calling 기능을 활용하여 날씨, 주식, 뉴스 등 다양한 외부 API를 LLM에 연결하는 실전 튜토리얼입니다. 코드 예제와 함께 설명합니다.',
    titleEn: 'Integrating External APIs with LLMs using Function Calling Instead of Plugins',
    url: 'https://hashnode.com/example/function-calling',
    score: 480,
    tags: ['openai', 'function-calling', 'api-integration', 'chatgpt'],
    createdAtSource: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '9분',
    },
  },
  {
    id: '9',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국발 초고속 비전 트랜스포머, 기존 대비 3배 빠른 추론 속도',
    summaryKoBody: '이미지 분류와 객체 탐지에서 뛰어난 성능을 보이는 경량화된 Vision Transformer 모델입니다.',
    titleEn: 'Ultra-Fast Vision Transformer with 3x Faster Inference Speed',
    url: 'https://github.com/example/fast-vit',
    score: 890,
    tags: ['vision-transformer', 'computer-vision', 'pytorch', 'deep-learning'],
    createdAtSource: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 4200,
      language: 'Chinese',
    },
  },
  {
    id: '10',
    itemType: 'REPO',
    source: 'github',
    category: 'DEVOPS_SRE',
    summaryKoTitle: '쿠버네티스 클러스터 자동 스케일링 및 비용 최적화 도구',
    summaryKoBody: 'AWS, GCP, Azure 등 멀티 클라우드 환경에서 자동으로 리소스를 조정하고 비용을 절감합니다.',
    titleEn: 'Kubernetes Auto-Scaling and Cost Optimization Tool for Multi-Cloud',
    url: 'https://github.com/example/k8s-optimizer',
    score: 1100,
    tags: ['kubernetes', 'autoscaling', 'cost-optimization', 'golang'],
    createdAtSource: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 5600,
      language: 'English',
    },
  },
  {
    id: '11',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: 'Go 언어 기반 분산 캐싱 시스템, Redis 대비 10배 빠른 성능',
    summaryKoBody: '메모리 효율적인 데이터 구조와 최적화된 네트워크 프로토콜로 극한의 성능을 달성했습니다.',
    titleEn: 'Distributed Caching System in Go - 10x Faster Than Redis',
    url: 'https://github.com/example/go-cache',
    score: 980,
    tags: ['golang', 'caching', 'distributed-systems', 'performance'],
    createdAtSource: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 3100,
      language: 'English',
    },
  },
  {
    id: '12',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국 개발자들이 만든 오픈소스 멀티모달 LLM, GPT-4V 수준 달성',
    summaryKoBody: '이미지, 텍스트, 오디오를 동시에 처리할 수 있는 멀티모달 대규모 언어 모델입니다.',
    titleEn: 'Open Source Multimodal LLM Achieving GPT-4V Level Performance',
    url: 'https://github.com/example/multimodal-llm',
    score: 1350,
    tags: ['multimodal', 'llm', 'vision-language', 'pytorch'],
    createdAtSource: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 8900,
      language: 'Chinese',
    },
  },
  {
    id: '13',
    itemType: 'REPO',
    source: 'github',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'Terraform 대안으로 떠오르는 차세대 IaC 도구',
    summaryKoBody: '더 간결한 문법과 빠른 실행 속도를 제공하며, 멀티 클라우드 환경을 완벽 지원합니다.',
    titleEn: 'Next-Generation Infrastructure as Code Tool - Terraform Alternative',
    url: 'https://github.com/example/new-iac',
    score: 760,
    tags: ['infrastructure-as-code', 'terraform', 'devops', 'cloud'],
    createdAtSource: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 2800,
      language: 'English',
    },
  },
  {
    id: '14',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: '마이크로서비스 간 통신을 위한 초경량 메시지 브로커',
    summaryKoBody: 'RabbitMQ나 Kafka보다 설정이 간단하고 메모리 사용량이 1/10 수준입니다.',
    titleEn: 'Lightweight Message Broker for Microservices Communication',
    url: 'https://github.com/example/micro-broker',
    score: 620,
    tags: ['message-broker', 'microservices', 'rust', 'distributed-systems'],
    createdAtSource: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 1900,
      language: 'English',
    },
  },
  {
    id: '15',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국 텍스트 임베딩 모델, 영어 모델 대비 20% 성능 향상',
    summaryKoBody: '중국어와 영어를 모두 지원하며, RAG 시스템에 최적화된 고품질 임베딩을 생성합니다.',
    titleEn: 'High-Performance Text Embedding Model for Chinese and English',
    url: 'https://github.com/example/text-embedding-cn',
    score: 1020,
    tags: ['embedding', 'nlp', 'rag', 'chinese'],
    createdAtSource: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 6700,
      language: 'Chinese',
    },
  },
  {
    id: '16',
    itemType: 'BLOG',
    source: 'hackernews',
    category: 'BACKEND',
    summaryKoTitle: 'PostgreSQL 16의 새로운 파티셔닝 기능으로 쿼리 성능 3배 향상',
    summaryKoBody: '대용량 데이터베이스에서 파티셔닝을 효율적으로 활용하는 방법과 실제 벤치마크 결과를 공유합니다.',
    titleEn: 'PostgreSQL 16 Partitioning: 3x Query Performance Boost',
    url: 'https://news.ycombinator.com/item?id=12346',
    score: 820,
    tags: ['postgresql', 'database', 'partitioning', 'performance'],
    createdAtSource: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 98,
      readTime: '11분',
    },
  },
  {
    id: '17',
    itemType: 'REPO',
    source: 'github',
    category: 'DEVOPS_SRE',
    summaryKoTitle: '실시간 로그 분석을 위한 고성능 스트리밍 파이프라인',
    summaryKoBody: 'ELK 스택 대비 5배 빠른 로그 처리 속도를 제공하는 Rust 기반 도구입니다.',
    titleEn: 'High-Performance Log Streaming Pipeline - 5x Faster Than ELK',
    url: 'https://github.com/example/log-stream',
    score: 710,
    tags: ['logging', 'rust', 'streaming', 'observability'],
    createdAtSource: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 2400,
      language: 'English',
    },
  },
  {
    id: '18',
    itemType: 'DISCUSSION',
    source: 'reddit',
    category: 'AI_LLM',
    summaryKoTitle: 'GPT-4 대비 70% 저렴한 비용으로 동일한 품질 달성한 파인튜닝 전략',
    summaryKoBody: '오픈소스 모델을 활용하여 특정 도메인에서 GPT-4 수준의 성능을 내는 방법을 설명합니다.',
    titleEn: 'Achieving GPT-4 Quality at 70% Lower Cost with Fine-tuning',
    url: 'https://reddit.com/r/machinelearning/example2',
    score: 890,
    tags: ['fine-tuning', 'llm', 'cost-optimization', 'gpt-4'],
    createdAtSource: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    metadata: {
      upvotes: 312,
      comments: 145,
    },
  },
  {
    id: '19',
    itemType: 'BLOG',
    source: 'medium',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'eBPF를 활용한 네트워크 성능 모니터링 완벽 가이드',
    summaryKoBody: '커널 레벨에서 네트워크 트래픽을 분석하고 병목 지점을 찾는 실전 기법을 다룹니다.',
    titleEn: 'Complete Guide to Network Performance Monitoring with eBPF',
    url: 'https://medium.com/example/ebpf-networking',
    score: 540,
    tags: ['ebpf', 'networking', 'performance', 'linux'],
    createdAtSource: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '18분',
    },
  },
  {
    id: '20',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: '타입스크립트로 만든 경량 GraphQL 서버, Apollo 대비 메모리 1/3',
    summaryKoBody: '최소한의 의존성으로 빠르게 GraphQL API를 구축할 수 있는 프레임워크입니다.',
    titleEn: 'Lightweight GraphQL Server in TypeScript - 1/3 Memory vs Apollo',
    url: 'https://github.com/example/graphql-lite',
    score: 680,
    tags: ['graphql', 'typescript', 'api', 'performance'],
    createdAtSource: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 1850,
      language: 'English',
    },
  },
  {
    id: '21',
    itemType: 'BLOG',
    source: 'devto',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'GitHub Actions로 복잡한 멀티 클라우드 배포 자동화하기',
    summaryKoBody: 'AWS, GCP, Azure에 동시 배포하는 워크플로우 구성과 비용 최적화 팁을 공유합니다.',
    titleEn: 'Automating Multi-Cloud Deployments with GitHub Actions',
    url: 'https://dev.to/example/multi-cloud-deploy',
    score: 420,
    tags: ['github-actions', 'ci-cd', 'multi-cloud', 'automation'],
    createdAtSource: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '14분',
    },
  },
  {
    id: '22',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국산 오픈소스 음성 인식 모델, Whisper 수준의 정확도',
    summaryKoBody: '중국어와 영어 모두 뛰어난 인식률을 보이며, 엣지 디바이스에서도 실행 가능합니다.',
    titleEn: 'Open Source Speech Recognition Model Matching Whisper Accuracy',
    url: 'https://github.com/example/speech-recognition-cn',
    score: 1180,
    tags: ['speech-recognition', 'whisper', 'audio', 'deep-learning'],
    createdAtSource: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 7200,
      language: 'Chinese',
    },
  },
  {
    id: '23',
    itemType: 'DISCUSSION',
    source: 'hackernews',
    category: 'OTHER',
    summaryKoTitle: '시니어 개발자가 알려주는 기술 부채 관리 전략 10가지',
    summaryKoBody: '20년 경력 개발자가 다양한 프로젝트에서 기술 부채를 효과적으로 줄인 사례를 공유합니다.',
    titleEn: '10 Strategies for Managing Technical Debt from a Senior Developer',
    url: 'https://news.ycombinator.com/item?id=12347',
    score: 670,
    tags: ['technical-debt', 'best-practices', 'software-engineering'],
    createdAtSource: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 201,
    },
  },
  {
    id: '24',
    itemType: 'BLOG',
    source: 'hashnode',
    category: 'BACKEND',
    summaryKoTitle: 'Node.js 21의 네이티브 테스트 러너로 Jest 대체하기',
    summaryKoBody: '별도의 라이브러리 없이 Node.js 내장 테스트 기능만으로 충분한 테스트 커버리지를 달성하는 방법입니다.',
    titleEn: 'Replacing Jest with Node.js 21 Native Test Runner',
    url: 'https://hashnode.com/example/nodejs-test',
    score: 510,
    tags: ['nodejs', 'testing', 'jest', 'javascript'],
    createdAtSource: new Date(Date.now() - 35 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '13분',
    },
  },
  {
    id: '25',
    itemType: 'REPO',
    source: 'github',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'Terraform 상태 파일을 안전하게 관리하는 오픈소스 백엔드',
    summaryKoBody: 'S3 대신 자체 호스팅 가능한 암호화된 상태 저장소를 제공합니다.',
    titleEn: 'Self-Hosted Encrypted Backend for Terraform State Files',
    url: 'https://github.com/example/terraform-backend',
    score: 590,
    tags: ['terraform', 'state-management', 'security', 'golang'],
    createdAtSource: new Date(Date.now() - 38 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 1650,
      language: 'English',
    },
  },
  {
    id: '26',
    itemType: 'BLOG',
    source: 'medium',
    category: 'AI_LLM',
    summaryKoTitle: 'LangChain 없이 순수 Python으로 RAG 시스템 구축하기',
    summaryKoBody: '의존성을 최소화하고 RAG의 핵심 원리를 이해하며 직접 구현하는 튜토리얼입니다.',
    titleEn: 'Building RAG Systems with Pure Python Without LangChain',
    url: 'https://medium.com/example/rag-pure-python',
    score: 730,
    tags: ['rag', 'python', 'vector-db', 'embeddings'],
    createdAtSource: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '20분',
    },
  },
  {
    id: '27',
    itemType: 'DISCUSSION',
    source: 'reddit',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'Kubernetes 운영 3년차가 말하는 실전 장애 대응 사례',
    summaryKoBody: '실제 프로덕션에서 발생한 장애와 해결 과정, 그리고 예방 전략을 상세히 설명합니다.',
    titleEn: 'Real-World Kubernetes Incident Response After 3 Years in Production',
    url: 'https://reddit.com/r/kubernetes/example',
    score: 780,
    tags: ['kubernetes', 'incident-response', 'production', 'sre'],
    createdAtSource: new Date(Date.now() - 42 * 60 * 60 * 1000).toISOString(),
    metadata: {
      upvotes: 289,
      comments: 112,
    },
  },
  {
    id: '28',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: 'Go로 작성된 실시간 협업 편집기 엔진, OT 알고리즘 구현',
    summaryKoBody: 'Google Docs와 같은 실시간 동시 편집 기능을 구현할 수 있는 라이브러리입니다.',
    titleEn: 'Real-time Collaborative Editing Engine in Go with OT Algorithm',
    url: 'https://github.com/example/collab-engine',
    score: 850,
    tags: ['golang', 'realtime', 'operational-transform', 'websocket'],
    createdAtSource: new Date(Date.now() - 45 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 3300,
      language: 'English',
    },
  },
  {
    id: '29',
    itemType: 'BLOG',
    source: 'devto',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'AWS Lambda 콜드 스타트를 99% 줄인 최적화 기법',
    summaryKoBody: '프로비저닝, 레이어 최적화, 런타임 선택 등 실전에서 검증된 방법들을 소개합니다.',
    titleEn: 'Reducing AWS Lambda Cold Starts by 99% with Optimization Techniques',
    url: 'https://dev.to/example/lambda-coldstart',
    score: 640,
    tags: ['aws-lambda', 'serverless', 'performance', 'optimization'],
    createdAtSource: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '16분',
    },
  },
  {
    id: '30',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국발 코드 생성 LLM, GitHub Copilot 수준의 정확도',
    summaryKoBody: 'Python, JavaScript, Java 등 다양한 언어를 지원하며 로컬에서 실행 가능합니다.',
    titleEn: 'Code Generation LLM Matching GitHub Copilot Accuracy',
    url: 'https://github.com/example/code-llm-cn',
    score: 1420,
    tags: ['code-generation', 'llm', 'copilot', 'programming'],
    createdAtSource: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 9100,
      language: 'Chinese',
    },
  },
  {
    id: '31',
    itemType: 'BLOG',
    source: 'hashnode',
    category: 'BACKEND',
    summaryKoTitle: 'WebSocket vs Server-Sent Events: 실시간 통신 기술 비교',
    summaryKoBody: '각 기술의 장단점과 적합한 사용 사례를 실제 구현 예제와 함께 설명합니다.',
    titleEn: 'WebSocket vs Server-Sent Events: Choosing the Right Real-time Tech',
    url: 'https://hashnode.com/example/websocket-sse',
    score: 480,
    tags: ['websocket', 'sse', 'realtime', 'comparison'],
    createdAtSource: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '10분',
    },
  },
  {
    id: '32',
    itemType: 'DISCUSSION',
    source: 'hackernews',
    category: 'OTHER',
    summaryKoTitle: '원격 근무 5년차 개발자의 생산성 향상 루틴',
    summaryKoBody: '홈 오피스 환경 구축부터 시간 관리, 운동, 정신 건강까지 종합적인 가이드입니다.',
    titleEn: 'Productivity Routines from 5 Years of Remote Software Development',
    url: 'https://news.ycombinator.com/item?id=12348',
    score: 560,
    tags: ['remote-work', 'productivity', 'work-life-balance'],
    createdAtSource: new Date(Date.now() - 55 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 178,
    },
  },
  {
    id: '33',
    itemType: 'REPO',
    source: 'github',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'CI/CD 파이프라인 보안 취약점 자동 스캔 도구',
    summaryKoBody: '컨테이너 이미지, 의존성, 설정 파일의 보안 문제를 실시간으로 탐지합니다.',
    titleEn: 'Automated Security Scanner for CI/CD Pipelines',
    url: 'https://github.com/example/cicd-security',
    score: 720,
    tags: ['security', 'ci-cd', 'scanning', 'devops'],
    createdAtSource: new Date(Date.now() - 58 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 2700,
      language: 'English',
    },
  },
  {
    id: '34',
    itemType: 'BLOG',
    source: 'medium',
    category: 'BACKEND',
    summaryKoTitle: 'Rust와 WebAssembly로 브라우저에서 고성능 연산 수행하기',
    summaryKoBody: '이미지 처리, 암호화 등 무거운 작업을 클라이언트에서 빠르게 처리하는 방법을 다룹니다.',
    titleEn: 'High-Performance Computing in Browser with Rust and WebAssembly',
    url: 'https://medium.com/example/rust-wasm',
    score: 610,
    tags: ['rust', 'webassembly', 'wasm', 'performance'],
    createdAtSource: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '17분',
    },
  },
  {
    id: '35',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: 'LLM 출력 검증 및 구조화를 위한 Python 라이브러리',
    summaryKoBody: 'JSON 스키마 기반으로 LLM 응답을 자동 검증하고 재시도 로직을 제공합니다.',
    titleEn: 'Python Library for LLM Output Validation and Structuring',
    url: 'https://github.com/example/llm-validator',
    score: 870,
    tags: ['llm', 'validation', 'python', 'json-schema'],
    createdAtSource: new Date(Date.now() - 62 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 4100,
      language: 'English',
    },
  },
  {
    id: '36',
    itemType: 'DISCUSSION',
    source: 'reddit',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'GCP에서 AWS로 마이그레이션한 실제 경험담과 비용 비교',
    summaryKoBody: '6개월간의 마이그레이션 프로젝트에서 배운 교훈과 양쪽 클라우드의 차이점을 설명합니다.',
    titleEn: 'Real Experience Migrating from GCP to AWS with Cost Comparison',
    url: 'https://reddit.com/r/devops/migration',
    score: 690,
    tags: ['gcp', 'aws', 'migration', 'cloud-comparison'],
    createdAtSource: new Date(Date.now() - 65 * 60 * 60 * 1000).toISOString(),
    metadata: {
      upvotes: 234,
      comments: 97,
    },
  },
  {
    id: '37',
    itemType: 'BLOG',
    source: 'devto',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'Docker 멀티 스테이지 빌드로 이미지 크기 80% 줄이기',
    summaryKoBody: '실전 예제와 함께 빌드 최적화 기법과 레이어 캐싱 전략을 소개합니다.',
    titleEn: 'Reducing Docker Image Size by 80% with Multi-Stage Builds',
    url: 'https://dev.to/example/docker-multistage',
    score: 520,
    tags: ['docker', 'optimization', 'containers', 'best-practices'],
    createdAtSource: new Date(Date.now() - 68 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '12분',
    },
  },
  {
    id: '38',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: 'Elixir 기반 분산 작업 큐, Sidekiq보다 빠른 처리 속도',
    summaryKoBody: 'Phoenix 앱과 완벽하게 통합되며 에러 재시도와 스케줄링 기능을 제공합니다.',
    titleEn: 'Distributed Job Queue in Elixir - Faster Than Sidekiq',
    url: 'https://github.com/example/elixir-queue',
    score: 580,
    tags: ['elixir', 'job-queue', 'distributed-systems', 'phoenix'],
    createdAtSource: new Date(Date.now() - 70 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 2200,
      language: 'English',
    },
  },
  {
    id: '39',
    itemType: 'BLOG',
    source: 'hashnode',
    category: 'AI_LLM',
    summaryKoTitle: 'Stable Diffusion 모델 파인튜닝으로 브랜드 맞춤 이미지 생성',
    summaryKoBody: '적은 데이터셋으로도 특정 스타일의 이미지를 생성할 수 있는 LoRA 기법을 설명합니다.',
    titleEn: 'Brand-Specific Image Generation with Stable Diffusion Fine-tuning',
    url: 'https://hashnode.com/example/sd-finetuning',
    score: 660,
    tags: ['stable-diffusion', 'fine-tuning', 'lora', 'image-generation'],
    createdAtSource: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '15분',
    },
  },
  {
    id: '40',
    itemType: 'DISCUSSION',
    source: 'hackernews',
    category: 'OTHER',
    summaryKoTitle: '주니어 개발자가 시니어로 성장하기 위한 로드맵',
    summaryKoBody: '기술 스킬뿐만 아니라 커뮤니케이션, 멘토링, 아키텍처 설계 능력까지 포괄적으로 다룹니다.',
    titleEn: 'Roadmap for Junior Developers to Grow into Senior Roles',
    url: 'https://news.ycombinator.com/item?id=12349',
    score: 920,
    tags: ['career', 'growth', 'junior-to-senior', 'software-engineering'],
    createdAtSource: new Date(Date.now() - 75 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 267,
    },
  },
  {
    id: '41',
    itemType: 'REPO',
    source: 'github',
    category: 'INFRA_CLOUD',
    summaryKoTitle: '중국산 경량 서비스 메시, Istio 대비 메모리 사용량 1/5',
    summaryKoBody: 'Envoy 기반이지만 훨씬 간단한 설정과 낮은 리소스 사용량을 자랑합니다.',
    titleEn: 'Lightweight Service Mesh - 1/5 Memory Usage vs Istio',
    url: 'https://github.com/example/light-mesh-cn',
    score: 940,
    tags: ['service-mesh', 'istio', 'kubernetes', 'microservices'],
    createdAtSource: new Date(Date.now() - 78 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 5400,
      language: 'Chinese',
    },
  },
  {
    id: '42',
    itemType: 'BLOG',
    source: 'medium',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'OpenTelemetry로 구축하는 통합 관측성 플랫폼',
    summaryKoBody: '메트릭, 로그, 트레이스를 하나의 플랫폼에서 관리하는 방법을 단계별로 설명합니다.',
    titleEn: 'Building Unified Observability Platform with OpenTelemetry',
    url: 'https://medium.com/example/opentelemetry',
    score: 570,
    tags: ['opentelemetry', 'observability', 'tracing', 'metrics'],
    createdAtSource: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '19분',
    },
  },
  {
    id: '43',
    itemType: 'REPO',
    source: 'github',
    category: 'BACKEND',
    summaryKoTitle: 'FastAPI를 능가하는 Python 비동기 웹 프레임워크',
    summaryKoBody: 'Rust의 성능과 Python의 생산성을 결합한 하이브리드 접근법을 사용합니다.',
    titleEn: 'Python Async Web Framework Outperforming FastAPI',
    url: 'https://github.com/example/fast-python',
    score: 1050,
    tags: ['python', 'fastapi', 'async', 'web-framework'],
    createdAtSource: new Date(Date.now() - 82 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 6800,
      language: 'English',
    },
  },
  {
    id: '44',
    itemType: 'DISCUSSION',
    source: 'reddit',
    category: 'AI_LLM',
    summaryKoTitle: 'LLM 프롬프트 엔지니어링 실전 팁 50가지',
    summaryKoBody: '다양한 사용 사례에서 검증된 프롬프트 작성 기법과 예제를 모아둔 가이드입니다.',
    titleEn: '50 Practical Tips for LLM Prompt Engineering',
    url: 'https://reddit.com/r/machinelearning/prompts',
    score: 1120,
    tags: ['prompt-engineering', 'llm', 'gpt', 'best-practices'],
    createdAtSource: new Date(Date.now() - 85 * 60 * 60 * 1000).toISOString(),
    metadata: {
      upvotes: 456,
      comments: 189,
    },
  },
  {
    id: '45',
    itemType: 'BLOG',
    source: 'devto',
    category: 'INFRA_CLOUD',
    summaryKoTitle: 'Cloudflare Workers로 엣지에서 동적 콘텐츠 생성하기',
    summaryKoBody: 'CDN 엣지에서 서버리스 함수를 실행하여 응답 속도를 극대화하는 방법입니다.',
    titleEn: 'Generating Dynamic Content at the Edge with Cloudflare Workers',
    url: 'https://dev.to/example/cf-workers',
    score: 490,
    tags: ['cloudflare', 'edge-computing', 'serverless', 'cdn'],
    createdAtSource: new Date(Date.now() - 88 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '11분',
    },
  },
  {
    id: '46',
    itemType: 'REPO',
    source: 'github',
    category: 'DEVOPS_SRE',
    summaryKoTitle: 'Ansible 대체 도구, YAML 대신 Python으로 인프라 관리',
    summaryKoBody: '타입 안정성과 IDE 지원을 제공하며 기존 Ansible 플레이북 마이그레이션도 쉽습니다.',
    titleEn: 'Infrastructure Management in Python - Ansible Alternative',
    url: 'https://github.com/example/infra-python',
    score: 780,
    tags: ['ansible', 'python', 'infrastructure', 'automation'],
    createdAtSource: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 3600,
      language: 'English',
    },
  },
  {
    id: '47',
    itemType: 'BLOG',
    source: 'hashnode',
    category: 'BACKEND',
    summaryKoTitle: 'gRPC-Web으로 브라우저와 gRPC 서버 직접 통신하기',
    summaryKoBody: 'REST API 없이 브라우저에서 바로 gRPC 서비스를 호출하는 방법과 장단점을 설명합니다.',
    titleEn: 'Direct Browser-to-gRPC Communication with gRPC-Web',
    url: 'https://hashnode.com/example/grpc-web',
    score: 530,
    tags: ['grpc', 'grpc-web', 'api', 'browser'],
    createdAtSource: new Date(Date.now() - 92 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '13분',
    },
  },
  {
    id: '48',
    itemType: 'DISCUSSION',
    source: 'hackernews',
    category: 'OTHER',
    summaryKoTitle: '개발자를 위한 효과적인 문서화 전략과 도구',
    summaryKoBody: 'API 문서, 아키텍처 다이어그램, 온보딩 가이드 등 각 상황에 맞는 문서화 방법을 소개합니다.',
    titleEn: 'Effective Documentation Strategies and Tools for Developers',
    url: 'https://news.ycombinator.com/item?id=12350',
    score: 640,
    tags: ['documentation', 'technical-writing', 'tools', 'best-practices'],
    createdAtSource: new Date(Date.now() - 95 * 60 * 60 * 1000).toISOString(),
    metadata: {
      comments: 156,
    },
  },
  {
    id: '49',
    itemType: 'REPO',
    source: 'github',
    category: 'AI_LLM',
    summaryKoTitle: '중국 오픈소스 이미지 생성 모델, SDXL 대비 2배 빠른 속도',
    summaryKoBody: '동일한 품질의 이미지를 절반의 시간에 생성하며 VRAM 사용량도 적습니다.',
    titleEn: 'Image Generation Model 2x Faster Than SDXL',
    url: 'https://github.com/example/fast-diffusion-cn',
    score: 1290,
    tags: ['diffusion', 'image-generation', 'sdxl', 'pytorch'],
    createdAtSource: new Date(Date.now() - 98 * 60 * 60 * 1000).toISOString(),
    metadata: {
      stars: 8300,
      language: 'Chinese',
    },
  },
  {
    id: '50',
    itemType: 'BLOG',
    source: 'medium',
    category: 'BACKEND',
    summaryKoTitle: 'Event Sourcing과 CQRS 패턴을 실무에 적용한 경험담',
    summaryKoBody: '이커머스 플랫폼에서 복잡한 비즈니스 로직을 관리하기 위해 두 패턴을 도입한 과정을 공유합니다.',
    titleEn: 'Implementing Event Sourcing and CQRS in Production E-commerce',
    url: 'https://medium.com/example/event-sourcing-cqrs',
    score: 710,
    tags: ['event-sourcing', 'cqrs', 'architecture', 'microservices'],
    createdAtSource: new Date(Date.now() - 100 * 60 * 60 * 1000).toISOString(),
    metadata: {
      readTime: '22분',
    },
  },
];
